import { User, Expense } from './types';

export const users: User[] = [
  {
    id: 'usr_1',
    name: 'Admin User',
    email: 'admin@expenseflow.com',
    avatarUrl: 'https://picsum.photos/seed/user1/100/100',
    role: 'Admin',
  },
  {
    id: 'usr_2',
    name: 'Michael Scott',
    email: 'michael.scott@expenseflow.com',
    avatarUrl: 'https://picsum.photos/seed/user2/100/100',
    role: 'Manager',
    managerId: 'usr_1',
  },
  {
    id: 'usr_3',
    name: 'Dwight Schrute',
    email: 'dwight.schrute@expenseflow.com',
    avatarUrl: 'https://picsum.photos/seed/user3/100/100',
    role: 'Employee',
    managerId: 'usr_2',
  },
  {
    id: 'usr_4',
    name: 'Jim Halpert',
    email: 'jim.halpert@expenseflow.com',
    avatarUrl: 'https://picsum.photos/seed/user4/100/100',
    role: 'Employee',
    managerId: 'usr_2',
  },
  {
    id: 'usr_5',
    name: 'Pam Beesly',
    email: 'pam.beesly@expenseflow.com',
    avatarUrl: 'https://picsum.photos/seed/user5/100/100',
    role: 'Employee',
    managerId: 'usr_2',
  },
];

export const expenses: Expense[] = [
    {
        id: 'exp_1',
        userId: 'usr_3',
        amount: 85.50,
        currency: 'USD',
        category: 'Travel',
        description: 'Client meeting lunch',
        date: '2024-05-15T12:30:00Z',
        status: 'Approved',
        vendor: 'The Capital Grille',
        approvers: [{ userId: 'usr_2', status: 'Approved', comment: 'Looks good.' }],
    },
    {
        id: 'exp_2',
        userId: 'usr_4',
        amount: 250.00,
        currency: 'USD',
        category: 'Supplies',
        description: 'New office chairs',
        date: '2024-05-14T10:00:00Z',
        status: 'Pending',
        vendor: 'Staples',
        approvers: [{ userId: 'usr_2', status: 'Pending' }],
    },
    {
        id: 'exp_3',
        userId: 'usr_5',
        amount: 30.25,
        currency: 'USD',
        category: 'Food',
        description: 'Team coffee run',
        date: '2024-05-13T09:15:00Z',
        status: 'Rejected',
        vendor: 'Starbucks',
        approvers: [{ userId: 'usr_2', status: 'Rejected', comment: 'This is not a valid business expense.' }],
    },
    {
        id: 'exp_4',
        userId: 'usr_3',
        amount: 550.00,
        currency: 'CAD',
        category: 'Training',
        description: 'React Conf 2024 Ticket',
        date: '2024-05-12T14:00:00Z',
        status: 'Pending',
        vendor: 'React Conferences Inc.',
        approvers: [{ userId: 'usr_2', status: 'Pending' }],
    },
    {
        id: 'exp_5',
        userId: 'usr_4',
        amount: 1200.00,
        currency: 'EUR',
        category: 'Travel',
        description: 'Flight to Berlin for conference',
        date: '2024-05-11T18:45:00Z',
        status: 'Approved',
        vendor: 'Lufthansa',
        approvers: [{ userId: 'usr_2', status: 'Approved' }],
    },
    {
        id: 'exp_6',
        userId: 'usr_3',
        amount: 75.00,
        currency: 'USD',
        category: 'Software',
        description: 'Figma Subscription',
        date: '2024-04-30T11:00:00Z',
        status: 'Approved',
        vendor: 'Figma',
        approvers: [{ userId: 'usr_2', status: 'Approved' }],
    },
];

export function getUserById(id: string) {
    return users.find(user => user.id === id);
}
