// This file is automatically generated. Do not modify it manually.

// IMPORTANT: This configuration is for client-side use only. Do not expose any server-side secrets.
// The security of your Firebase app is enforced by your Firebase Security Rules, not by this configuration.

export const firebaseConfig = {
  "apiKey": "AIzaSyBQUlyhrhcuIsRF4PlqWAaP2yvrJupt3Po",
  "authDomain": "next-app-starter-c89b2.firebaseapp.com",
  "projectId": "next-app-starter-c89b2",
  "storageBucket": "next-app-starter-c89b2.appspot.com",
  "messagingSenderId": "1002874138138",
  "appId": "1:1002874138138:web:75f3a033f2425c27773223",
  "measurementId": "G-56EMLE0R5J"
};
